"""add_gmail_import

Revision ID: 2e3b699a4583
Revises: 20260717
Create Date: 2026-08-01 02:23:29.055001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3b699a4583'
down_revision: Union[str, None] = '20260717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_credentials',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_gmail_credentials_user_id'), 'gmail_credentials', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('gmail_message_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_transactions_gmail_message_id'), 'transactions', ['gmail_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_gmail_message_id'), table_name='transactions')
    op.drop_column('transactions', 'gmail_message_id')
    op.drop_index(op.f('ix_gmail_credentials_user_id'), table_name='gmail_credentials')
    op.drop_table('gmail_credentials')
    # ### end Alembic commands ###
