"""add_portfolio_tables

Revision ID: 18f9c812a635
Revises: 7ae3fad8e906
Create Date: 2026-06-07 00:21:46.901542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f9c812a635'
down_revision: Union[str, None] = '7ae3fad8e906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('average_buy_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('invested_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gain_loss', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gain_loss_percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('dividend_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend_date', sa.Date(), nullable=True),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    op.create_index(op.f('ix_holdings_user_id'), 'holdings', ['user_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('invested_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gain_loss', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('milestone_type', sa.String(length=50), nullable=True),
    sa.Column('milestone_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_user_id'), 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_symbol'), 'watchlist', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_symbol'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_portfolio_snapshots_user_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_holdings_user_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_table('holdings')
    # ### end Alembic commands ###
